# Generated by Django 4.1.1 on 2022-09-23 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_agenda', '0003_posteo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posteo',
            new_name='Posteo_animales',
        ),
    ]
