# Generated by Django 4.1.1 on 2022-09-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agenda', '0004_rename_posteo_posteo_animales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mascota',
        ),
        migrations.AlterField(
            model_name='posteo_animales',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
