# Generated by Django 4.1.1 on 2022-09-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agenda', '0005_delete_mascota_alter_posteo_animales_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo_animales',
            name='autor',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='posteo_animales',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='posteo_animales',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
