# Generated by Django 4.1.1 on 2022-09-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agenda', '0008_posteo_interacciones_delete_planta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo_animales',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='posteo_interacciones',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='posteo_interacciones',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imagenes'),
        ),
        migrations.AlterField(
            model_name='posteo_plantas',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
