# Generated by Django 4.1.1 on 2022-09-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agenda', '0009_alter_posteo_animales_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo_interacciones',
            name='imagen',
            field=models.ImageField(upload_to='imagenes'),
        ),
    ]
